import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Container, Modal, Row } from "@nextui-org/react";
import Hero from "../components/Hero";
import Faq from "../components/Faq";
import {
  Navbar,
  Button,
  Link,
  Text,
  Card,
  Radio,
  Avatar,
  Dropdown,
  Switch,
  useTheme,
} from "@nextui-org/react";
import { useTheme as useNextTheme } from "next-themes";
import Footer from "../components/layout/Footer";
import NavbarComponent from "../components/layout/NavbarComponent";
import ThreeStories from "../components/ThreeStories";
import VectorStories from "../components/VectorStories";
import Layout from "../components/layout/Layout";
import DashboardLayout from "../components/layout/DashboardLayout";
const Home = () => {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();
  const collapseItems = [
    "Profile",
    "Dashboard",
    "Activity",
    "Analytics",
    "System",
    "Deployments",
    "My Settings",
    "Team Settings",
    "Help & Feedback",
    "Log Out",
  ];

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-[1280px] mx-auto">
        <Hero />
        <VectorStories />
        <ThreeStories />
        <Faq />
      </main>
    </Container>
  );
};
export default Home;
